In [10]:
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
%reload_ext autoreload


In [12]:
import numpy as np
import random
import scipy.special
from collections import Counter

In [13]:
from tree import Tree, generate_root_sequence, simulate_sequences, mutate_sequence, coalescence_tree_with_sequences


In [14]:
sample_size = 5
num_states = 4  # For DNA 
seq_length = 10
mutation_rate = 0.01

tree, sequences = coalescence_tree_with_sequences(sample_size, num_states, seq_length, mutation_rate)
print("Coalescence Tree:", vars(tree))
print("Sequences at the leaves:", sequences)



Coalescence Tree: {'left_child': array([-1, -1, -1, -1, -1,  3,  5,  2,  1]), 'right_child': array([-1, -1, -1, -1, -1,  4,  0,  6,  7]), 'parent': array([ 6,  8,  7,  5,  5,  6,  7,  8, -1]), 'time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12603799, 0.5562777 , 0.7277489 , 2.84052126]), 'sample_size': 5, 'n_states': 4, 'sequences': []}
Sequences at the leaves: [[1 2 1 3 2 1 0 3 2 3]
 [1 2 1 3 2 1 0 3 2 3]
 [1 2 1 3 2 1 0 3 2 3]
 [1 2 1 3 2 1 0 3 2 3]
 [1 2 1 3 2 1 0 3 2 3]]


In [15]:
import numpy as np
import random
import scipy.special
import math

def compute_log_likelihood_for_thetas(tree, theta_values):
    log_likelihoods = []

    for theta in theta_values:
        # Calculate the log likelihood with the given mutation rate (theta)
        likelihood = tree.compute_likelihood(theta)
        if likelihood > 0:
            log_likelihood = math.log(likelihood)
        else:
            log_likelihood = float('-inf')  # Log of zero is -inf
        print(f"Theta: {theta}, Likelihood: {likelihood}, Log Likelihood: {log_likelihood}")
        log_likelihoods.append(log_likelihood)

    return log_likelihoods

In [16]:

# Define the sequences
sequences = [
    "12112121211212121122",
    "12112121211211121122",
    "12112121211211111122"
]

# Convert sequences to numerical format
num_sequences = [[int(base) for base in seq] for seq in sequences]

# Define the number of leaves for each sequence
num_leaves = [13, 21, 16]

# Create the full sequence array
full_sequences = []
for seq, count in zip(num_sequences, num_leaves):
    full_sequences.extend([seq] * count)

print("Sequences:")
for seq in full_sequences:
    print(seq)


Sequences:
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2]
[1, 2, 1, 1, 

In [17]:

# Initialize the tree
sample_size = 50
n_states = 2  # For example, binary states
tree = Tree(sample_size, n_states=n_states, sequences=full_sequences)  # Fix here

# Define theta values to test
theta_values = [0.1, 0.2, 0.5, 1.0, 2.0]

# Compute log likelihoods for thetas
log_likelihoods = compute_log_likelihood_for_thetas(tree, theta_values)

# Output the results
for theta, log_likelihood in zip(theta_values, log_likelihoods):
    print(f"Theta: {theta}, Log Likelihood: {log_likelihood}")


Leaf 0 Likelihoods for site 0: [0. 1.]
Leaf 1 Likelihoods for site 0: [0. 1.]
Leaf 2 Likelihoods for site 0: [0. 1.]
Leaf 3 Likelihoods for site 0: [0. 1.]
Leaf 4 Likelihoods for site 0: [0. 1.]
Leaf 5 Likelihoods for site 0: [0. 1.]
Leaf 6 Likelihoods for site 0: [0. 1.]
Leaf 7 Likelihoods for site 0: [0. 1.]
Leaf 8 Likelihoods for site 0: [0. 1.]
Leaf 9 Likelihoods for site 0: [0. 1.]
Leaf 10 Likelihoods for site 0: [0. 1.]
Leaf 11 Likelihoods for site 0: [0. 1.]
Leaf 12 Likelihoods for site 0: [0. 1.]
Leaf 13 Likelihoods for site 0: [0. 1.]
Leaf 14 Likelihoods for site 0: [0. 1.]
Leaf 15 Likelihoods for site 0: [0. 1.]
Leaf 16 Likelihoods for site 0: [0. 1.]
Leaf 17 Likelihoods for site 0: [0. 1.]
Leaf 18 Likelihoods for site 0: [0. 1.]
Leaf 19 Likelihoods for site 0: [0. 1.]
Leaf 20 Likelihoods for site 0: [0. 1.]
Leaf 21 Likelihoods for site 0: [0. 1.]
Leaf 22 Likelihoods for site 0: [0. 1.]
Leaf 23 Likelihoods for site 0: [0. 1.]
Leaf 24 Likelihoods for site 0: [0. 1.]
Leaf 25 Li

In [19]:
for t in range(num_states):
    print(f"State {t}:")

range(0, 4)